# -*- coding: utf-8 -*-
"""重建 outputs/release/manifest.json：v20、source_commit、8 点 key numbers、全部文件 SHA-256。

字段说明：
  source_commit = 生成此 release 数据的分析脚本与数据所在的 git commit（即权威源版本）。
  manifest 自身可能在同一或更晚的 commit 中被提交；不记录 release_commit 以避免自引用。
"""
import hashlib, json, os, subprocess, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RELEASE = ROOT / 'outputs' / 'release'

def sha256(p):
    return hashlib.sha256(open(p, 'rb').read()).hexdigest()

def git_head():
    """直接读 .git 下的 HEAD/refs，不调用 git 进程（避免在共享盘上生成 index.lock）。"""
    g = ROOT / '.git'
    try:
        head = (g / 'HEAD').read_text().strip()
        if not head.startswith('ref:'):
            return head[:7]
        ref = head.split(' ', 1)[1]
        loose = g / ref
        if loose.exists():
            return loose.read_text().strip()[:7]
        for line in (g / 'packed-refs').read_text().splitlines():
            if line.endswith(' ' + ref):
                return line.split(' ', 1)[0][:7]
    except OSError:
        pass
    return 'unknown'

files = []
for root, dirs, names in os.walk(RELEASE):
    for n in sorted(names):
        if n == 'manifest.json':
            continue
        fp = os.path.join(root, n)
        rel = os.path.relpath(fp, RELEASE).replace('\\', '/')
        files.append({'path': rel, 'size': os.path.getsize(fp), 'sha256': sha256(fp)})
files.sort(key=lambda x: x['path'])

manifest = {
    'version': ('v22 (2026-10-03): test-set plain U-Net = selected lr 1e-3 (archPU1e3); offset and field-of-view '
                'ladders re-scored at case-level validation-calibrated thresholds; all nine figures regenerated by '
                'scripts/make_figures_v22.py'),
    'date': '2026-10-03',
    'source_commit': git_head(),
    '_commit_note': 'source_commit = git commit containing the analysis scripts and source data for this release. '
                    'The manifest file itself is committed in the same or a later commit.',
    'source_of_truth': (
        'outputs/analysis_full/symmetric_analysis.json (CV tables), analysis_test/symmetric_analysis_applied.json '
        '(held-out test; released as symmetric_analysis_test_applied.json), analysis_scope/scope_analysis_merged2.json, '
        'analysis_scope/diag_offset_allarms.json + diag_offset.json + offset_paired_stats.json, '
        'analysis/effect_uncertainty.json, '
        'analysis_full/noise_floor.json, analysis/generalisation_table.json (8-point) + LIDC reference, '
        'analysis/qubiq_all_effects.json + qubiq_trend.json + qubiq_agreement_index.json + disagreement_index.json'
    ),
    'unit': 'case-level (patches averaged within case)',
    'key_numbers': {
        'evaluation_target_A_fixed05_CV': 25.58,
        'evaluation_target_A_fixed05_test': 28.58,
        'threshold_A_V4_CV': 9.42,
        'threshold_A_V4_test': 9.99,
        'supervision_target_CV_test': [2.65, 3.12],
        'architecture_range_CV_test': [0.96, 1.19],
        'noise_floor_2sigma': 1.19,
        'noise_floor_ci': [0.97, 1.59],
        'headline_ratios': '7.1x supervision / 18.7x architecture (test, conservative 22.29 numerator)',
        'joint_bootstrap_ratios_124cases': {'supervision': [7.0, [5.8, 8.7]], 'architecture': [15.6, [9.3, 30.9]]},
        'fov_conservative': 22.29,
        'fov_position_invariant': 43.54,
        'offset_median_8px': 26.40,
        'offset_d40_paired_fivefold': {'diff': 60.79, 'ci95': [55.47, 65.80], 'dz': 2.58},
        'qubiq_points': 8,
        'qubiq_tasks': ['LIDC(reference)', 'brain-growth', 'kidney', 'brain-tumor-task1',
                        'brain-tumor-task2', 'brain-tumor-task3', 'prostate-task1', 'prostate-task2'],
        'qubiq_trend_7QUBIQ': {'spearman_rho': -0.7857, 'exact_perm_p': 0.048},
        'qubiq_trend_8pts_incl_LIDC': {'spearman_rho': -0.857, 'exact_perm_p': 0.011},
        'qubiq_ratio_trend': 'not significant (7pt rho=-0.07 p=0.91; 8pt rho=-0.31 p=0.46)',
        'holm_significant_20': 11,
        'disagreement_8pts': [0.333, 0.489, 0.868, 0.777, 0.175, 0.636, 0.960, 0.766],
    },
    'csv_policy': (
        'This package contains aggregated JSONs, paper figures, and per-case CSVs for all QUBIQ tasks '
        '(brain-growth, kidney, brain-tumor t1-3, prostate t1-2) in subdirectories qubiq_*/. '
        'LIDC full per-case records (~600 MB) are intended for Zenodo; the aggregated LIDC results are in '
        'symmetric_analysis.json and cross_validation_report.json. QUBIQ raw images are NOT included '
        '(grand-challenge.org terms); only per-case evaluation outputs are released.'
    ),
    'files': files,
}

out = RELEASE / 'manifest.json'
with open(out, 'w', encoding='utf-8') as f:
    json.dump(manifest, f, indent=1, ensure_ascii=False)
print('manifest.json 重建完成:')
print('  version       =', manifest['version'])
print('  source_commit =', manifest['source_commit'])
print('  文件数         =', len(files))
print('  QUBIQ 8 点     =', manifest['key_numbers']['qubiq_trend_8pts_incl_LIDC'])
